### ISSUE TITLE
视频下载失败

### ISSUE THREAD

**Issue by ybqdren** [vcharfred/tiktok-video-tool#1]
控制台报错: 

```
java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONObject.getJSONArray(String)" because the return value of "com.alibaba.fastjson.JSONObject.parseObject(String)" is null
	at top.vchar.util.TikTokHttpUtil.extractVideoUrl(TikTokHttpUtil.java:85)
	at top.vchar.AppUI$2.actionPerformed(AppUI.java:81)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
```

请求 body 为空
![图片](https://user-images.githubusercontent.com/46752566/214836014-a7c79b1e-5b43-4509-8ed4-4149b05d95d3.png)

请求下载的URL:
```
1.76 eBt:/ 销冠到大年初五才回老家，回家的路上还是没忍住啊。。。  https://v.douyin.com/kEk7fuE/ 复制此链接，打开Dou音搜索，直接观看视频！
```

**Comment by vcharfred** [comment]
由于抖音接口升级了，现在请求接口需要x-bogus等参数
